export const CURRENCY_PRICE_RANGE = {
  USD: { min: 5, step: 5 },
  EUR: { min: 5, step: 5 },
  GBP: { min: 5, step: 5 },
};

export const CURRENCY_SYMBOL = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  CHF: 'CHF',
};

export const GENRE_OPTIONS = [
  { value: 'ELECTRONIC', key: 'ELECTRONIC', text: 'Electronic' },
  { value: 'REGGAE', key: 'REGGAE', text: 'Reggae' },
  { value: 'NONMUSIC', key: 'NONMUSIC', text: 'Non-Music' },
  { value: 'CHILDRENS', key: 'CHILDRENS', text: "Children's" },
  { value: 'HIPHOP', key: 'HIPHOP', text: 'Hiphop' },
  { value: 'LATIN', key: 'LATIN', text: 'Latin' },
  { value: 'POP', key: 'POP', text: 'Pop' },
  { value: 'FOLK', key: 'FOLK', text: 'Folk' },
  { value: 'JAZZ', key: 'JAZZ', text: 'Jazz' },
  { value: 'FUNK', key: 'FUNK', text: 'Funk' },
  { value: 'CLASSICAL', key: 'CLASSICAL', text: 'Classical' },
  { value: 'STAGE', key: 'STAGE', text: 'Stage' },
  { value: 'ROCK', key: 'ROCK', text: 'Rock' },
  { value: 'BLUES', key: 'BLUES', text: 'Blues' },
  { value: 'BRASS', key: 'BRASS', text: 'Brass' },
];

export const FORMAT_OPTIONS = [
  { value: 'VINYL', key: 'VINYL', text: 'Vinyl' },
  { value: 'ACETATE', key: 'ACETATE', text: 'Acetate' },
  { value: 'FLEXIDISC', key: 'FLEXIDISC', text: 'Flexi-disc' },
  { value: 'CD', key: 'CD', text: 'CD' },
  { value: 'DVD', key: 'DVD', text: 'DVD' },
  { value: 'BLURAY', key: 'BLURAY', text: 'Blu-Ray' },
  { value: 'SACD', key: 'SACD', text: 'SACD' },
];

export const COUNTRY_OPTIONS = [
  { value: 'AF', key: 'AF', text: 'Afghanistan' },
  { value: 'AL', key: 'AL', text: 'Albania' },
  { value: 'DZ', key: 'DZ', text: 'Algeria' },
  { value: 'AS', key: 'AS', text: 'American Samoa' },
  { value: 'AD', key: 'AD', text: 'Andorra' },
  { value: 'AO', key: 'AO', text: 'Angola' },
  { value: 'AI', key: 'AI', text: 'Anguilla' },
  { value: 'AQ', key: 'AQ', text: 'Antarctica' },
  { value: 'AG', key: 'AG', text: 'Antigua and Barbuda' },
  { value: 'AR', key: 'AR', text: 'Argentina' },
  { value: 'AM', key: 'AM', text: 'Armenia' },
  { value: 'AW', key: 'AW', text: 'Aruba' },
  { value: 'AU', key: 'AU', text: 'Australia' },
  { value: 'AT', key: 'AT', text: 'Austria' },
  { value: 'AZ', key: 'AZ', text: 'Azerbaijan' },
  { value: 'BS', key: 'BS', text: 'Bahamas (the)' },
  { value: 'BH', key: 'BH', text: 'Bahrain' },
  { value: 'BD', key: 'BD', text: 'Bangladesh' },
  { value: 'BB', key: 'BB', text: 'Barbados' },
  { value: 'BY', key: 'BY', text: 'Belarus' },
  { value: 'BE', key: 'BE', text: 'Belgium' },
  { value: 'BZ', key: 'BZ', text: 'Belize' },
  { value: 'BJ', key: 'BJ', text: 'Benin' },
  { value: 'BM', key: 'BM', text: 'Bermuda' },
  { value: 'BT', key: 'BT', text: 'Bhutan' },
  { value: 'BO', key: 'BO', text: 'Bolivia (Plurinational State of)' },
  { value: 'BQ', key: 'BQ', text: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'BA', key: 'BA', text: 'Bosnia and Herzegovina' },
  { value: 'BW', key: 'BW', text: 'Botswana' },
  { value: 'BV', key: 'BV', text: 'Bouvet Island' },
  { value: 'BR', key: 'BR', text: 'Brazil' },
  { value: 'IO', key: 'IO', text: 'British Indian Ocean Territory (the)' },
  { value: 'BN', key: 'BN', text: 'Brunei Darussalam' },
  { value: 'BG', key: 'BG', text: 'Bulgaria' },
  { value: 'BF', key: 'BF', text: 'Burkina Faso' },
  { value: 'BI', key: 'BI', text: 'Burundi' },
  { value: 'CV', key: 'CV', text: 'Cabo Verde' },
  { value: 'KH', key: 'KH', text: 'Cambodia' },
  { value: 'CM', key: 'CM', text: 'Cameroon' },
  { value: 'CA', key: 'CA', text: 'Canada' },
  { value: 'KY', key: 'KY', text: 'Cayman Islands (the)' },
  { value: 'CF', key: 'CF', text: 'Central African Republic (the)' },
  { value: 'TD', key: 'TD', text: 'Chad' },
  { value: 'CL', key: 'CL', text: 'Chile' },
  { value: 'CN', key: 'CN', text: 'China' },
  { value: 'CX', key: 'CX', text: 'Christmas Island' },
  { value: 'CC', key: 'CC', text: 'Cocos (Keeling) Islands (the)' },
  { value: 'CO', key: 'CO', text: 'Colombia' },
  { value: 'KM', key: 'KM', text: 'Comoros (the)' },
  { value: 'CD', key: 'CD', text: 'Congo (the Democratic Republic of the)' },
  { value: 'CG', key: 'CG', text: 'Congo (the)' },
  { value: 'CK', key: 'CK', text: 'Cook Islands (the)' },
  { value: 'CR', key: 'CR', text: 'Costa Rica' },
  { value: 'HR', key: 'HR', text: 'Croatia' },
  { value: 'CU', key: 'CU', text: 'Cuba' },
  { value: 'CW', key: 'CW', text: 'Curaçao' },
  { value: 'CY', key: 'CY', text: 'Cyprus' },
  { value: 'CZ', key: 'CZ', text: 'Czechia' },
  { value: 'CI', key: 'CI', text: "Côte d'Ivoire" },
  { value: 'DK', key: 'DK', text: 'Denmark' },
  { value: 'DJ', key: 'DJ', text: 'Djibouti' },
  { value: 'DM', key: 'DM', text: 'Dominica' },
  { value: 'DO', key: 'DO', text: 'Dominican Republic (the)' },
  { value: 'EC', key: 'EC', text: 'Ecuador' },
  { value: 'EG', key: 'EG', text: 'Egypt' },
  { value: 'SV', key: 'SV', text: 'El Salvador' },
  { value: 'GQ', key: 'GQ', text: 'Equatorial Guinea' },
  { value: 'ER', key: 'ER', text: 'Eritrea' },
  { value: 'EE', key: 'EE', text: 'Estonia' },
  { value: 'SZ', key: 'SZ', text: 'Eswatini' },
  { value: 'ET', key: 'ET', text: 'Ethiopia' },
  { value: 'FK', key: 'FK', text: 'Falkland Islands (the) [Malvinas]' },
  { value: 'FO', key: 'FO', text: 'Faroe Islands (the)' },
  { value: 'FJ', key: 'FJ', text: 'Fiji' },
  { value: 'FI', key: 'FI', text: 'Finland' },
  { value: 'FR', key: 'FR', text: 'France' },
  { value: 'GF', key: 'GF', text: 'French Guiana' },
  { value: 'PF', key: 'PF', text: 'French Polynesia' },
  { value: 'TF', key: 'TF', text: 'French Southern Territories (the)' },
  { value: 'GA', key: 'GA', text: 'Gabon' },
  { value: 'GM', key: 'GM', text: 'Gambia (the)' },
  { value: 'GE', key: 'GE', text: 'Georgia' },
  { value: 'DE', key: 'DE', text: 'Germany' },
  { value: 'GH', key: 'GH', text: 'Ghana' },
  { value: 'GI', key: 'GI', text: 'Gibraltar' },
  { value: 'GR', key: 'GR', text: 'Greece' },
  { value: 'GL', key: 'GL', text: 'Greenland' },
  { value: 'GD', key: 'GD', text: 'Grenada' },
  { value: 'GP', key: 'GP', text: 'Guadeloupe' },
  { value: 'GU', key: 'GU', text: 'Guam' },
  { value: 'GT', key: 'GT', text: 'Guatemala' },
  { value: 'GG', key: 'GG', text: 'Guernsey' },
  { value: 'GN', key: 'GN', text: 'Guinea' },
  { value: 'GW', key: 'GW', text: 'Guinea-Bissau' },
  { value: 'GY', key: 'GY', text: 'Guyana' },
  { value: 'HT', key: 'HT', text: 'Haiti' },
  { value: 'HM', key: 'HM', text: 'Heard Island and McDonald Islands' },
  { value: 'VA', key: 'VA', text: 'Holy See (the)' },
  { value: 'HN', key: 'HN', text: 'Honduras' },
  { value: 'HK', key: 'HK', text: 'Hong Kong' },
  { value: 'HU', key: 'HU', text: 'Hungary' },
  { value: 'IS', key: 'IS', text: 'Iceland' },
  { value: 'IN', key: 'IN', text: 'India' },
  { value: 'ID', key: 'ID', text: 'Indonesia' },
  { value: 'IR', key: 'IR', text: 'Iran (Islamic Republic of)' },
  { value: 'IQ', key: 'IQ', text: 'Iraq' },
  { value: 'IE', key: 'IE', text: 'Ireland' },
  { value: 'IM', key: 'IM', text: 'Isle of Man' },
  { value: 'IL', key: 'IL', text: 'Israel' },
  { value: 'IT', key: 'IT', text: 'Italy' },
  { value: 'JM', key: 'JM', text: 'Jamaica' },
  { value: 'JP', key: 'JP', text: 'Japan' },
  { value: 'JE', key: 'JE', text: 'Jersey' },
  { value: 'JO', key: 'JO', text: 'Jordan' },
  { value: 'KZ', key: 'KZ', text: 'Kazakhstan' },
  { value: 'KE', key: 'KE', text: 'Kenya' },
  { value: 'KI', key: 'KI', text: 'Kiribati' },
  {
    value: 'KP',
    key: 'KP',
    text: "Korea (the Democratic People's Republic of)",
  },
  { value: 'KR', key: 'KR', text: 'Korea (the Republic of)' },
  { value: 'KW', key: 'KW', text: 'Kuwait' },
  { value: 'KG', key: 'KG', text: 'Kyrgyzstan' },
  { value: 'LA', key: 'LA', text: "Lao People's Democratic Republic (the)" },
  { value: 'LV', key: 'LV', text: 'Latvia' },
  { value: 'LB', key: 'LB', text: 'Lebanon' },
  { value: 'LS', key: 'LS', text: 'Lesotho' },
  { value: 'LR', key: 'LR', text: 'Liberia' },
  { value: 'LY', key: 'LY', text: 'Libya' },
  { value: 'LI', key: 'LI', text: 'Liechtenstein' },
  { value: 'LT', key: 'LT', text: 'Lithuania' },
  { value: 'LU', key: 'LU', text: 'Luxembourg' },
  { value: 'MO', key: 'MO', text: 'Macao' },
  { value: 'MG', key: 'MG', text: 'Madagascar' },
  { value: 'MW', key: 'MW', text: 'Malawi' },
  { value: 'MY', key: 'MY', text: 'Malaysia' },
  { value: 'MV', key: 'MV', text: 'Maldives' },
  { value: 'ML', key: 'ML', text: 'Mali' },
  { value: 'MT', key: 'MT', text: 'Malta' },
  { value: 'MH', key: 'MH', text: 'Marshall Islands (the)' },
  { value: 'MQ', key: 'MQ', text: 'Martinique' },
  { value: 'MR', key: 'MR', text: 'Mauritania' },
  { value: 'MU', key: 'MU', text: 'Mauritius' },
  { value: 'YT', key: 'YT', text: 'Mayotte' },
  { value: 'MX', key: 'MX', text: 'Mexico' },
  { value: 'FM', key: 'FM', text: 'Micronesia (Federated States of)' },
  { value: 'MD', key: 'MD', text: 'Moldova (the Republic of)' },
  { value: 'MC', key: 'MC', text: 'Monaco' },
  { value: 'MN', key: 'MN', text: 'Mongolia' },
  { value: 'ME', key: 'ME', text: 'Montenegro' },
  { value: 'MS', key: 'MS', text: 'Montserrat' },
  { value: 'MA', key: 'MA', text: 'Morocco' },
  { value: 'MZ', key: 'MZ', text: 'Mozambique' },
  { value: 'MM', key: 'MM', text: 'Myanmar' },
  { value: 'NA', key: 'NA', text: 'Namibia' },
  { value: 'NR', key: 'NR', text: 'Nauru' },
  { value: 'NP', key: 'NP', text: 'Nepal' },
  { value: 'NL', key: 'NL', text: 'Netherlands (the)' },
  { value: 'NC', key: 'NC', text: 'New Caledonia' },
  { value: 'NZ', key: 'NZ', text: 'New Zealand' },
  { value: 'NI', key: 'NI', text: 'Nicaragua' },
  { value: 'NE', key: 'NE', text: 'Niger (the)' },
  { value: 'NG', key: 'NG', text: 'Nigeria' },
  { value: 'NU', key: 'NU', text: 'Niue' },
  { value: 'NF', key: 'NF', text: 'Norfolk Island' },
  { value: 'MP', key: 'MP', text: 'Northern Mariana Islands (the)' },
  { value: 'NO', key: 'NO', text: 'Norway' },
  { value: 'OM', key: 'OM', text: 'Oman' },
  { value: 'PK', key: 'PK', text: 'Pakistan' },
  { value: 'PW', key: 'PW', text: 'Palau' },
  { value: 'PS', key: 'PS', text: 'Palestine, State of' },
  { value: 'PA', key: 'PA', text: 'Panama' },
  { value: 'PG', key: 'PG', text: 'Papua New Guinea' },
  { value: 'PY', key: 'PY', text: 'Paraguay' },
  { value: 'PE', key: 'PE', text: 'Peru' },
  { value: 'PH', key: 'PH', text: 'Philippines (the)' },
  { value: 'PN', key: 'PN', text: 'Pitcairn' },
  { value: 'PL', key: 'PL', text: 'Poland' },
  { value: 'PT', key: 'PT', text: 'Portugal' },
  { value: 'PR', key: 'PR', text: 'Puerto Rico' },
  { value: 'QA', key: 'QA', text: 'Qatar' },
  { value: 'MK', key: 'MK', text: 'Republic of North Macedonia' },
  { value: 'RO', key: 'RO', text: 'Romania' },
  { value: 'RU', key: 'RU', text: 'Russian Federation (the)' },
  { value: 'RW', key: 'RW', text: 'Rwanda' },
  { value: 'RE', key: 'RE', text: 'Réunion' },
  { value: 'BL', key: 'BL', text: 'Saint Barthélemy' },
  {
    value: 'SH',
    key: 'SH',
    text: 'Saint Helena, Ascension and Tristan da Cunha',
  },
  { value: 'KN', key: 'KN', text: 'Saint Kitts and Nevis' },
  { value: 'LC', key: 'LC', text: 'Saint Lucia' },
  { value: 'MF', key: 'MF', text: 'Saint Martin (French part)' },
  { value: 'PM', key: 'PM', text: 'Saint Pierre and Miquelon' },
  { value: 'VC', key: 'VC', text: 'Saint Vincent and the Grenadines' },
  { value: 'WS', key: 'WS', text: 'Samoa' },
  { value: 'SM', key: 'SM', text: 'San Marino' },
  { value: 'ST', key: 'ST', text: 'Sao Tome and Principe' },
  { value: 'SA', key: 'SA', text: 'Saudi Arabia' },
  { value: 'SN', key: 'SN', text: 'Senegal' },
  { value: 'RS', key: 'RS', text: 'Serbia' },
  { value: 'SC', key: 'SC', text: 'Seychelles' },
  { value: 'SL', key: 'SL', text: 'Sierra Leone' },
  { value: 'SG', key: 'SG', text: 'Singapore' },
  { value: 'SX', key: 'SX', text: 'Sint Maarten (Dutch part)' },
  { value: 'SK', key: 'SK', text: 'Slovakia' },
  { value: 'SI', key: 'SI', text: 'Slovenia' },
  { value: 'SB', key: 'SB', text: 'Solomon Islands' },
  { value: 'SO', key: 'SO', text: 'Somalia' },
  { value: 'ZA', key: 'ZA', text: 'South Africa' },
  {
    value: 'GS',
    key: 'GS',
    text: 'South Georgia and the South Sandwich Islands',
  },
  { value: 'SS', key: 'SS', text: 'South Sudan' },
  { value: 'ES', key: 'ES', text: 'Spain' },
  { value: 'LK', key: 'LK', text: 'Sri Lanka' },
  { value: 'SD', key: 'SD', text: 'Sudan (the)' },
  { value: 'SR', key: 'SR', text: 'Suriname' },
  { value: 'SJ', key: 'SJ', text: 'Svalbard and Jan Mayen' },
  { value: 'SE', key: 'SE', text: 'Sweden' },
  { value: 'CH', key: 'CH', text: 'Switzerland' },
  { value: 'SY', key: 'SY', text: 'Syrian Arab Republic' },
  { value: 'TW', key: 'TW', text: 'Taiwan' },
  { value: 'TJ', key: 'TJ', text: 'Tajikistan' },
  { value: 'TZ', key: 'TZ', text: 'Tanzania, United Republic of' },
  { value: 'TH', key: 'TH', text: 'Thailand' },
  { value: 'TL', key: 'TL', text: 'Timor-Leste' },
  { value: 'TG', key: 'TG', text: 'Togo' },
  { value: 'TK', key: 'TK', text: 'Tokelau' },
  { value: 'TO', key: 'TO', text: 'Tonga' },
  { value: 'TT', key: 'TT', text: 'Trinidad and Tobago' },
  { value: 'TN', key: 'TN', text: 'Tunisia' },
  { value: 'TR', key: 'TR', text: 'Turkey' },
  { value: 'TM', key: 'TM', text: 'Turkmenistan' },
  { value: 'TC', key: 'TC', text: 'Turks and Caicos Islands (the)' },
  { value: 'TV', key: 'TV', text: 'Tuvalu' },
  { value: 'UG', key: 'UG', text: 'Uganda' },
  { value: 'UA', key: 'UA', text: 'Ukraine' },
  { value: 'AE', key: 'AE', text: 'United Arab Emirates (the)' },
  {
    value: 'GB',
    key: 'GB',
    text: 'United Kingdom of Great Britain and Northern Ireland (the)',
  },
  {
    value: 'UM',
    key: 'UM',
    text: 'United States Minor Outlying Islands (the)',
  },
  { value: 'US', key: 'US', text: 'United States of America (the)' },
  { value: 'UY', key: 'UY', text: 'Uruguay' },
  { value: 'UZ', key: 'UZ', text: 'Uzbekistan' },
  { value: 'VU', key: 'VU', text: 'Vanuatu' },
  { value: 'VE', key: 'VE', text: 'Venezuela (Bolivarian Republic of)' },
  { value: 'VN', key: 'VN', text: 'Viet Nam' },
  { value: 'VG', key: 'VG', text: 'Virgin Islands (British)' },
  { value: 'VI', key: 'VI', text: 'Virgin Islands (U.S.)' },
  { value: 'WF', key: 'WF', text: 'Wallis and Futuna' },
  { value: 'EH', key: 'EH', text: 'Western Sahara' },
  { value: 'YE', key: 'YE', text: 'Yemen' },
  { value: 'ZM', key: 'ZM', text: 'Zambia' },
  { value: 'ZW', key: 'ZW', text: 'Zimbabwe' },
  { value: 'AX', key: 'AX', text: 'Åland Islands' },
];

export const CONDITION_OPTIONS = [
  { value: 'M', key: 'M', text: 'Mint (M)' },
  { value: 'NM', key: 'NM', text: 'Near Mint (NM)' },
  { value: 'VG_PLUS', key: 'VG_PLUS', text: 'Very Good Plus (VG+)' },
  { value: 'VG', key: 'VG', text: 'Very Good (VG)' },
  { value: 'G_PLUS', key: 'G_PLUS', text: 'Good Plus (G+)' },
  { value: 'G', key: 'G', text: 'Good (G)' },
  { value: 'FAIR', key: 'FAIR', text: 'Fair (F)' },
  { value: 'POOR', key: 'POOR', text: 'Poor (P)' },
];

export const PAYMENT_OPTIONS = [
  { value: 'CREDIT_CARD', key: 'CREDIT_CARD', text: 'Credit Card' },
  { value: 'PAYPAL', key: 'PAYPAL', text: 'Paypal' },
  { value: 'CASH', key: 'CASH', text: 'Cash' },
  { value: 'BANK_TRANSFER', key: 'BANK_TRANSFER', text: 'Bank Transfer' },
];

export const SHIPPING_OPTIONS = [
  {
    key: 'media mail',
    text: 'Media Mail - $7.00',
    value: 'Media Mail',
  },
];

export const ORDER_STATUS = [
  { value: 'NEW_ORDER', text: 'New Order', icon: 'star', color: 'teal' },
  {
    value: 'INVOICE_SENT',
    text: 'Invoice Sent',
    icon: 'list alternate outline',
    color: 'teal',
  },
  {
    value: 'PAYMENT_RECEIVED',
    text: 'Payment Received',
    icon: 'payment',
    color: 'teal',
  },
  { value: 'SHIPPED', text: 'Shipped', icon: 'shipping', color: 'teal' },
  { value: 'CANCELED', text: 'Canceled', icon: 'cancel', color: 'red' },
];

export const toHHMMSS = (secs) => {
  var sec_num = parseInt(secs, 10);
  var hours = Math.floor(sec_num / 3600);
  var minutes = Math.floor(sec_num / 60) % 60;
  var seconds = sec_num % 60;

  return [hours, minutes, seconds]
    .map((v) => (v < 10 ? '0' + v : v))
    .filter((v, i) => v !== '00' || i > 0)
    .join(':');
};

export const abbreviateNumber = (value) => {
  let newValue = value;
  if (value >= 1000) {
    let suffixes = ['', 'K', 'M', 'B', 'T'];
    let suffixNum = Math.floor(('' + value).length / 3);
    let shortValue = '';
    for (let precision = 2; precision >= 1; precision--) {
      shortValue = parseFloat(
        (suffixNum !== 0 ? value / Math.pow(1000, suffixNum) : value).toPrecision(precision)
      );
      let dotLessShortValue = (shortValue + '').replace(/[^a-zA-Z 0-9]+/g, '');
      if (dotLessShortValue.length <= 2) {
        break;
      }
    }
    if (shortValue % 1 !== 0) shortValue = shortValue.toFixed(1);
    newValue = shortValue + suffixes[suffixNum];
  }
  return newValue;
};

export const getTextWithValueInOptions = (value, options) => {
  return options.find((option) => option.value === value).text;
};
